Update features.md
openmrs/openmrs-android-client-user-guide pull request #13
Opened 2017-12-21 15:50 UTC by 0581raghav

2017-12-22 05:10 UTC, shivtej1505 requested changes
Nice progress :)
Please squash the two commits into one.

2017-12-22 05:10 UTC, shivtej1505 commented on features.md
> +   ![OpenMRS Android Client Offline login screen](https://user-images.githubusercontent.com/24738188/34084273-28d474aa-e3a3-11e7-90f1-218b29e1d36f.png)
Could you please make images somewhat smaller? They are taking too much space.

2017-12-22 05:10 UTC, shivtej1505 commented on features.md
> +   ![OpenMRS Android Client Offline login screen](https://user-images.githubusercontent.com/24738188/34084262-1732ca6c-e3a3-11e7-9e05-96d1ce0835c3.png)
Please change the URL shown in the screenshot to `https://demo.openmrs.org/openmrs` otherwise, it will create confusion.

2017-12-26 14:09 UTC, shivtej1505 commented
@0581raghav, can you squash the four commits into one?

2017-12-29 11:42 UTC, dkayiwa commented
@0581raghav did you see the merge conflicts?

2017-12-30 14:02 UTC, 0581raghav commented
@dkayiwa  Sorry, I will update the pull request after resolving merge conflict.

2017-12-31 05:46 UTC, f4ww4z commented
@0581raghav Just saw your fork is behind this repo's master. You can [see here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to pull the latest changes first :+1: .

2017-12-31 11:09 UTC, shivtej1505 approved these changes

2017-12-31 11:09 UTC, shivtej1505 commented
Thanks, @0581raghav, merging now!

2017-12-31 11:09 UTC, merged