AC-419: Fill up Troubleshooting
openmrs/openmrs-android-client-user-guide pull request #31
Opened 2018-11-19 12:29 UTC by Pilipino

Hi! I have already updated based on comments @f4ww4z. I am very sorry however, as I edited the changes on the browser, it seemed to not have synced properly.

## Description of what I changed

I have added a guide (troubleshooting.md) file that documents login issues and how to file issues This is a continuation of the PR filed at #28. I have made a new PR since the branch I was working on had rebase issues. However, I have already revised based on the comments by @f4ww4z. :)

## Issue I worked on

See https://issues.openmrs.org/browse/AC-419
See https://codein.withgoogle.com/dashboard/task-instances/6683284093272064/

2018-11-19 16:08 UTC, f4ww4z requested changes
Thanks for the changes @Pilipino . I have some additional comments, then you should be good to go.

2018-11-19 16:08 UTC, f4ww4z commented on troubleshooting.md
> +![OpenMRS Talk Android Client Filing Issue](assets/openmrs_talk_android_client_file_issue.png)
Can you hide the other irrelevant tabs in the screenshot? Sorry for not noticing this earlier.

2018-11-19 16:08 UTC, f4ww4z commented on troubleshooting.md
> +You could also refer to the part of the guide regarding features, which discusses how to test on the default test server [link](hhttps://openmrs.github.io/openmrs-android-client-user-guide/features.h
```suggestion
You may also refer to [this guide](https://openmrs.github.io/openmrs-android-client-user-guide/features.html) which discusses how to test on the default test server.
```

2018-11-19 16:08 UTC, f4ww4z commented on troubleshooting.md
> +You could also refer to the part of the guide regarding features, which discusses how to test on the default test server [link](hhttps://openmrs.github.io/openmrs-android-client-user-guide/features.h
You miss typed https :)

2018-11-19 16:08 UTC, f4ww4z commented on troubleshooting.md
> +
Newline is not needed here.

2018-11-19 23:09 UTC, Pilipino commented
I have updated @f4ww4z! Please advise! :D

2018-11-20 15:22 UTC, f4ww4z approved these changes

2018-11-20 15:23 UTC, merged